
[default]
workshop = [
    "450814997",  # CBA_A3's Workshop ID
    "3499977893", # Advanced Developer Tools
    "1779063631", # ZEN
    "3720138990", # AAS theme    
]

dlc = []
optionals = []

parameters = [
    "-noPause",
    "-noPauseAudio",
	"-debug",
	"-showScriptErrors",
]

[Altis]
extends = "default"
dlc = ["ws","rf", "vn"]
mission = "testMissionRF.Altis"